"""
Github: Niraj-kumbhar
------------------------
Script to send multiple emails with different/same attachments.
You can change subject, body of mail.
Provide recieptents list and data to attach in mail.

If you want to change or improve this script please create new branch and raise merge request.
"""

from email.mime.application import MIMEApplication
from email.policy import default
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import pandas as pd
from datetime import datetime

start = datetime.now()

def attachment_file(filename):
    # open the file to be sent 
    attachment = open(f'data/{filename}.pdf', "rb")
    return attachment

df = pd.read_excel('email_data.xlsx') # change if recieptent data file name is different
range_ = df.shape[0]
sender = open('security/sender_email.txt','r').read() # change if sender file name is different
pass_key = open('security/app_pass.txt','r').read()
constant_att = 'Evolutionary Psychology Takeaway Kit' #if any constant attachment is there for all mails
subject = open('email_content/mail_subject.txt','r').read() # change subject 
body = open('email_content/body.txt','r').read() #change body
logs = [] 

for i in range(range_):

    try:

        toaddr = df.Email[i] 
        
        msg = MIMEMultipart() 
        msg['From'] = sender 
        msg['To'] =  toaddr
        #fname = df.Name[i].split()[0]   #for future use : extracts recievers name

        msg['Subject'] = subject

        msg.attach(MIMEText(body, 'html')) # attach the body with the msg instance


        # instance of MIMEBase and named as p
        p = MIMEBase('application', 'octet-stream')

        filename = df.Name[i]
        attachment = attachment_file(filename)  # add file name
        
        #attach = MIMEApplication(attachment, _subtype="pdf")
        
        p.set_payload((attachment).read()) # To change the payload into encoded form
        encoders.encode_base64(p) # encode into base64
        
        p.add_header('Content-Disposition', "attachment; filename= %s.pdf" % filename)
        msg.attach(p)    # attach the instance 'p' to instance 'msg'

        # attaching constant file
        p = MIMEBase('application', 'octet-stream')
        cons = open(f'data/{constant_att}.pdf','rb')
        p.set_payload((cons).read())
        encoders.encode_base64(p) # encode into base64
        p.add_header('Content-Disposition', "attachment; filename= %s.pdf" % constant_att)
        msg.attach(p)
        
        # creates SMTP session
        s = smtplib.SMTP('smtp.gmail.com', 587)
        

        s.starttls()
        s.login(sender, pass_key) # Authentication of sender, generated by app password
        text = msg.as_string()
        s.sendmail(sender, toaddr, text) 
        s.quit() # terminating the session
        logs.append(1)

    except Exception as e:
        print(e)
        logs.append(0)
        continue

    finally:
        print(f'Completed: {df.Name}')

time_ = datetime.now() - start
print('*'*20,'\n')
print(f'time taken: {time_}')
logs_ = pd.DataFrame(list(zip(df.Email,df.Name,logs)),columns=['Email','Name','Status'])
logs_.to_excel('logs.xlsx')

